Pr/refactor tests
pksprojects/ElasticSwift pull request #13
Opened 2019-06-07 10:26 UTC by lubbo

I know there are many changes, but please take this pull into account to cleanup Request/Response interface, remove redundant code and have a working test case.
I tried to keep ES retro compatibility, but I can't test ES below 7.0, so probably something should be fixed.
Feel free to discuss about it

Thanks!

2019-06-08 19:01 UTC, prafsoni commented on Sources/ElasticSwift/ElasticSwift.swift
> +    public func makeGet<T: Codable>(fromIndex index: String, id: String) -> GetRequestBuilder<T> {
`ElasticSwift` strictly follows builders pattern. I see the convenience of the proposed change however I see these changes as overload and not as a replacement.

2019-06-08 19:03 UTC, prafsoni commented on Sources/ElasticSwift/Serialization/Serialization.swift
> +public protocol Serializer {
Great work! this change is awesome.

2019-06-08 19:28 UTC, prafsoni requested changes
Overall, I liked the changes proposed in the request. However, there a few minor changes that are needed. I have reflected them in comments.
Also, please make sure the PR doesn't have merge conflicts and is always submitted towards `dev`. I apologize for the inconvenience over branching as I only pointed towards `query-builders` branch but did make it clear to create pull request over dev branch.
To avoid these kinds of issues I am working on contributions guidelines document hoping to get it out soon.

2019-06-08 19:28 UTC, prafsoni commented on Sources/ElasticSwift/Requests/DeleteRequest.swift
> +    public func set(completionHandler: @escaping (DeleteResponse?, Error?) -> ()) -> Self {
Though, `Void` is a type alias for `()` we should use `Void` explicitly where the function should/does not return.

2019-06-10 01:52 UTC, closed without merging

2019-06-12 01:44 UTC, prafsoni commented
@lubbo I would appreciate if you could provide feedback on `v1.0.0-alpha.5`. Also, I am looking forward to this PR with changes. cheers!

2019-06-12 06:01 UTC, lubbo commented
Sure! This week I’m a bit busy but I’ll try my best